try:
    #raise ValueError
    sdf()
except Exception as e:
    print(e)
    print("Oops!  That was no valid number.  Try again...")
